# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b0d40783-4b9b-4649-83a5-a45cafa8ab1b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b0d40783-4b9b-4649-83a5-a45cafa8ab1b".device = "/dev/disk/by-uuid/b0d40783-4b9b-4649-83a5-a45cafa8ab1b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B84B-1006";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/fr3d/research" =
    { device = "/dev/disk/by-uuid/930ed788-8e94-4ecc-8080-d988dbb8779b";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8c2d44e7-30c2-4b2b-b742-a0095b40195c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
