# Generated by nixos-generate-config — replace with actual output from:
#   nixos-generate-config --show-hardware-config
# on the running Acer Nitro 5.
#
# Known layout:
#   sda  476.9G
#     sda1  470G  /home/anubis  (research + bulk files)
#   sdb  953.9G
#     sdb1  1G    /boot  (EFI system partition)
#     sdb2  4G    [SWAP]
#     sdb3  948.9G  /  (also hosts /nix/store)
#
# IMPORTANT: The PRIME bus IDs in modules/nixos/hardware.nix are PLACEHOLDERS.
# Run `lspci | grep -E 'VGA|3D'` on the hardware and update those values.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # sdb partitions — matches CLAUDE.md layout
  fileSystems."/" = {
    device = "/dev/sdb3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/sdb1";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [
    { device = "/dev/sdb2"; }
  ];

  # Secondary drive — research and other bulk files
  fileSystems."/home/anubis" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
