#git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gbd='git branch -d'
alias gcb='git checkout -b'
alias gc='git clone'
alias gcl='git clone --recurse-modules'
alias clean='git reset --hard && git clean -dfxx'
alias checkout='git checkout'
alias gpl='git pull'
alias gp='git push'
alias gs='git status'
alias gt='git tag'
alias gptf='git push --follow-tags'
alias glog='git log --date-order --pretty="format:%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset"'
alias gl='glog --graph'
alias gla='gl --all'
