alias context='kubectx'
alias k-shell='kubecolor run tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash'
alias cluster='kubecolor config get-clusters'
alias switch='kubectx'
alias k='kubecolor'
alias ka='kubecolor apply'
alias kaf='kubectl apply -f'
alias kd='kubectl describe'
alias kdel='kubectl delete'
alias kg='kubecolor get'
alias kgn='kubecolor get nodes -o wide'
alias kgp='kubecolor get pods -o wide'
alias kx='kubectl exec -it'
alias kdry='kubectl -o yaml --dry-run=client'
