#terraform
alias tf='op plugin run -- terraform'
alias tfi='op plugin run -- terraform init'
alias tfir='op plugin run -- terraform init -backend-config="remote.tfbackend" -upgrade'
alias tflint='terraform fmt && terraform validate'
alias tfv='terraform validate'
alias tfp='op plugin run -- terraform plan'
alias tfa='op plugin run -- terraform apply'
alias tfs='op plugin run -- terraform state'
alias tfsls='op plugin run -- terraform state list'
alias tfo='op plugin run -- terraform output'
alias tfd='op plugin run -- terraform destroy'
alias cost='infracost breakdown --path=.'
#alias docs='terraform-docs markdown table --hide modules --sort-by required --output-file README.md --output-mode inject ../'
