# zsh environment — ported from SCRT resources/zsh/{.zshrc,.zprofile,aliases,functions.sh}
# and resources/proxychains.conf. Package-manager aliases that assumed apt have
# been mapped to their Nix equivalents; everything else is kept verbatim so the
# muscle memory carries over.
{ config, lib, pkgs, ... }:
{
  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    TERM = "xterm-256color";
    TZ = "America/New_York";
  };

  programs.zsh = {
    enable = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    history = {
      size = 10000;
      save = 10000;
      path = "${config.home.homeDirectory}/.history";
      extended = true;
      ignoreDups = true;
      ignoreSpace = true;
      share = true;
    };

    oh-my-zsh = {
      enable = true;
      # autosuggestions/syntax-highlighting come from the native options above,
      # so they are intentionally omitted from this plugin list.
      plugins = [ "git" "tmux" "ssh" "python" "colorize" ];
    };

    shellAliases = {
      # daily use
      c = "clear";
      q = "exit";
      r = "exec zsh";
      v = "nvim";
      get = "curl -O -L";
      cat = "bat";
      weather = "curl https://wttr.in";
      public = "curl wtfismyip.com/text";
      download = "aria2c";
      home = "cd ~";

      # Nix replacements for the old apt aliases (kept on the same keys)
      i = "nix shell nixpkgs#"; # ad-hoc: `i ripgrep` -> drops you in a shell with it
      update = "nix flake update";
      upgrade = "sudo nixos-rebuild switch --flake .";

      # pentesting
      cme = "nxc"; # netexec provides the `nxc` binary
      port-scan = "sudo nmap -sC -sV -p- $IP -oN scan.txt";
      udp-scan = "sudo nmap -sU --top-ports 10 $IP -v -oN udp.scan.txt";
      stealth-scan = "sudo nmap --data-length 6 -T3 -A -ttl 64 -p- $IP -oN stealth-scan.txt";
      proxy = "proxychains4 -f ${config.home.homeDirectory}/.proxychains/proxychains.conf";
      serve = "sudo python3 -m http.server 8888";
      notepad = "nvim notes.md";

      # python
      py-virt = "python3 -m venv .venv && source .venv/bin/activate";
      freeze = "pip freeze > requirements.txt";
      py-install = "pip install -r requirements.txt";
      py-list = "pip3 list";
    };

    initContent = ''
      setopt AUTO_CD AUTO_PUSHD EXTENDED_GLOB NOMATCH MENU_COMPLETE
      setopt GLOB_DOTS INTERACTIVE_COMMENTS HIST_VERIFY PROMPT_SUBST
      unsetopt beep

      # vi key bindings
      bindkey -v

      ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ffffff,standout"
      ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE="20"
      ZSH_AUTOSUGGEST_USE_ASYNC=1

      # ---- operator helper functions (from functions.sh) ----
      extract() {
        if [ -f "$1" ]; then
          case "$1" in
            *.tar.bz2) tar xjf "$1" ;;
            *.tar.gz)  tar xzf "$1" ;;
            *.tar.xz)  tar xJf "$1" ;;
            *.bz2)     bunzip2 "$1" ;;
            *.gz)      gunzip "$1" ;;
            *.tar)     tar xf "$1" ;;
            *.tbz2)    tar xjf "$1" ;;
            *.tgz)     tar xzf "$1" ;;
            *.zip)     unzip "$1" ;;
            *.Z)       uncompress "$1" ;;
            *.7z)      7z x "$1" ;;
            *.xz)      xz -d -v "$1" ;;
            *)         echo "'$1' cannot be extracted via extract()" ;;
          esac
        else
          echo "'$1' is not a valid file"
        fi
      }

      up() { for _ in $(seq 1 "$1"); do cd ../; done; }

      virtual_env() {
        mkdir "$1" && cd "$1" && python3 -m venv .venv && source .venv/bin/activate
      }

      # Hardened miniserve file drop with a self-signed cert generated by cert-gen.
      webserver() {
        miniserve \
          -t "fr3d" -v -F -H -c monokai -p 9443 \
          --header "Cache-Control:no-cache" \
          --header "Server: Server" \
          --header "X-Frame-Options: DENY" \
          --header "Referrer-Policy: strict-origin-when-cross-origin" \
          --header "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload" \
          --auth-file ./auth.txt \
          --tls-cert "$HOME/.local/$1-cert.pem" \
          --tls-key "$HOME/.local/$1-key.pem" \
          -u
      }

      cert-gen() {
        mkcert -key-file "$HOME/.local/$1-key.pem" -cert-file "$HOME/.local/$1-cert.pem" localhost
      }

      timestamp() { date +%Y%m%d-%T; }
      encrypt_age() { age --passphrase --output "$1.enc" "$2"; }
      decrypt_age() { age -d "$1" > "$2"; }

      mkcd() {
        if [ -z "$1" ]; then echo "Enter a directory name";
        elif [ -d "$1" ]; then echo "'$1' already exists";
        else mkdir "$1" && cd "$1"; fi
      }

      # fzf completion tuning (from .zprofile)
      export FZF_COMPLETION_TRIGGER='..'
      export FZF_COMPLETION_OPTS='--border --info=inline'
      _fzf_compgen_path() { fd --hidden --follow --exclude ".git" . "$1"; }
      _fzf_compgen_dir()  { fd --type d --hidden --follow --exclude ".git" . "$1"; }
      _fzf_comprun() {
        local command=$1; shift
        case "$command" in
          cd)            fzf --preview 'tree -C {} | head -200' "$@" ;;
          export|unset)  fzf --preview "eval 'echo \$'{}" "$@" ;;
          ssh)           fzf --preview 'dig {}' "$@" ;;
          *)             fzf --preview 'bat -n --color=always {}' "$@" ;;
        esac
      }
    '';
  };

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    defaultCommand = "fd --hidden --follow --exclude .git";
    defaultOptions = [
      "--color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#262626"
      "--color=hl:#5fb079,hl+:#43fb00,info:#afaf87,marker:#87ff00"
      "--color=prompt:#06fd34,spinner:#f2ff5e,pointer:#fbfbfb,header:#87afaf"
      "--color=border:#28fe03,preview-fg:#f1f8f2,label:#aeaeae,query:#e97b7b"
      "--border=rounded"
      "--prompt=> "
      "--marker=>"
      "--pointer=◆"
    ];
  };

  # proxychains-ng default config (ported verbatim from resources/proxychains.conf)
  home.file.".proxychains/proxychains.conf".text = ''
    strict_chain
    proxy_dns
    remote_dns_subnet 224
    tcp_read_time_out 15000
    tcp_connect_time_out 8000

    [ProxyList]
    # add proxies here — type  ip  port  [user pass]
    http    127.0.0.1   8080
    socks5  127.0.0.1   9050
    socks4  127.0.0.1   1080
  '';
}
